import React from "react";

const TermsOfService = () => {
  const dateObj = new Date();
  const Section = ({ title, children }) => (
    <section className="bg-[#2A3744] p-6 rounded-xl shadow-lg">
      <h2 className="text-2xl font-semibold mb-4 border-b border-gray-600 pb-2">{title}</h2>
      <div className="space-y-4">{children}</div>
    </section>
  );

  return (
    <div className="bg-[#1E2931] text-white font-sans min-h-screen">
      <div className="max-w-4xl mx-auto p-6 md:p-12">
        <div className="text-center mb-12">
          <h1 className="text-5xl font-extrabold mb-4 bg-gradient-to-r from-blue-400 to-purple-500 bg-clip-text text-transparent">
            Terms of Service
          </h1>
          <p className="text-gray-300 text-lg">
            Effective date: <strong>{dateObj.toLocaleDateString()}</strong>
          </p>
        </div>

        <div className="text-gray-200 space-y-8">
          <Section title="Service summary">
            <p>
              Vircle.ai offers a context‑aware AI companion that learns routines, preferences, and relationships to provide proactive suggestions and emotionally intelligent conversations, optimized for frequent, lightweight interactions on mobile.
            </p>
          </Section>

          <Section title="Contracting entity and acceptance">
            <p>
              These Terms of Service govern access to and use of the Vircle mobile applications and related services (the “Service”) provided by ITWORKED YAZILIM IC VE DIS TICARET LIMITED SIRKETI, registered in Istanbul, Türkiye, operating the Vircle brand (“Vircle,” “we,” or “us”). By accessing or using the Service, an individual or entity (“user”) agrees to these Terms and the incorporated Privacy Policy. If these Terms are updated, continued use after the effective date constitutes acceptance of the updated terms.
            </p>
          </Section>

          <Section title="Eligibility and accounts">
            <ul className="list-disc list-inside space-y-3">
              <li><strong>Eligibility:</strong> Use is permitted only where legal and subject to eligibility rules set by the applicable app store distribution platform (Apple App Store or Google Play). Parental/guardian consent may be required where local law or store rules require it.</li>
              <li><strong>Account registration:</strong> Accounts may be created via Apple, Google, or email. Accurate and current information must be maintained.</li>
              <li><strong>Account security and sharing:</strong> Account sharing is prohibited. The account holder is responsible for all activity under the account and must keep credentials secure. Promptly notify Vircle of any unauthorized use or security incident.</li>
              <li><strong>Deletion:</strong> Account deletion can be initiated in‑app and will take effect without additional processing time, subject to lawful and safety‑related retention noted below.</li>
            </ul>
          </Section>

          <Section title="The Service">
            <ul className="list-disc list-inside space-y-3">
              <li><strong>Platforms and availability:</strong> The Service is available on iOS and Android. Minimum OS versions, device compatibility, and updates may change, and updates may be required for continued use.</li>
              <li><strong>No geographic restriction:</strong> Access is offered globally, subject to applicable law and export/sanctions compliance.</li>
              <li><strong>Modifications:</strong> Features may be added, changed, or discontinued at any time. Beta or labs features may be limited, experimental, or withdrawn without notice.</li>
            </ul>
          </Section>

          <Section title="AI nature, transparency, and safety">
            <ul className="list-disc list-inside space-y-3">
              <li><strong>AI‑generated content:</strong> Interactions and outputs are generated by artificial intelligence and may not be reviewed by humans.</li>
              <li><strong>No professional advice:</strong> Outputs are informational only, do not constitute professional advice (including medical, legal, financial, or other professional services), and are not a substitute for emergency services.</li>
              <li><strong>No guarantee:</strong> Vircle does not guarantee the accuracy, completeness, reliability, or availability of any output or recommendation, and makes no guarantee of results.</li>
              <li><strong>Safety:</strong> If outputs are harmful, offensive, or erroneous, stop using the Service and report the issue through the in‑app contact/reporting channel.</li>
            </ul>
          </Section>

          <Section title="Acceptable use">
            <p>Users must not:</p>
            <ul className="list-disc list-inside space-y-3 pl-4">
              <li>Violate any law, regulation, or rights of others.</li>
              <li>Engage in harassment, hate speech, threats, fraud, spam, phishing, or exploitation.</li>
              <li>Post, generate, or request non‑consensual intimate content (“NCII”), child sexual abuse material (CSAM), or content that sexualizes minors.</li>
              <li>Promote self‑harm, suicide, eating disorders, or other safety harms.</li>
              <li>Promote or support terrorism or violent extremism.</li>
              <li>Conduct doxxing or disclose personal data without authorization.</li>
              <li>Create or distribute malware or malicious code.</li>
              <li>Scrape, harvest, or bulk export content or outputs; attempt to bypass technical measures or rate limits.</li>
              <li>Reverse engineer, decompile, disassemble, or attempt to extract models, datasets, or system prompts; engage in prompt‑hacking or model extraction.</li>
              <li>Automate account creation or operate multi‑account farms.</li>
              <li>Create or disseminate misleading synthetic media (e.g., deepfakes) or manipulate content to deceive. Political persuasion and electioneering are restricted and may require clear labeling and are subject to removal.</li>
              <li>Create medical, legal, or financial agents without clear disclosure; users must not rely on such content without consulting qualified professionals.</li>
              <li>NSFW/adult content is not permitted.</li>
            </ul>
          </Section>
          
          <Section title="Impersonation">
            <p>
              Users may not impersonate real persons or entities in a manner likely to cause confusion or harm. If parody or satire is used, it must be clearly disclosed as such and may still be restricted.
            </p>
          </Section>

          <Section title="Community sharing">
            <p>
              If the Service enables sharing personas or chats, public content must comply with these Terms. Vircle may remove or restrict content, annotate, demote, or disable sharing at its discretion for safety, legality, or policy compliance.
            </p>
          </Section>

          <Section title="User content, outputs, and licenses">
             <ul className="list-disc list-inside space-y-3">
              <li><strong>User‑generated content (UGC):</strong> Users retain ownership of their inputs, uploads, and personas. Users grant Vircle a worldwide, non‑exclusive, royalty‑free, transferable and sublicensable license to host, store, process, reproduce, adapt, translate, display, and distribute UGC as necessary to provide, protect, maintain, and improve the Service, including for product improvement, and to comply with law.</li>
              <li><strong>Subprocessors/service providers:</strong> Vircle may sublicense rights to vetted service providers and model vendors as reasonably necessary to operate and improve features.</li>
              <li><strong>AI outputs:</strong> Subject to law and third‑party rights, Vircle grants users a non‑exclusive license to use outputs for personal, non‑commercial purposes, unless the app explicitly indicates a different license. No rights are granted to use outputs to train models, benchmark, or build competing services. Users must not remove notices or attributions where present.</li>
              <li><strong>Third‑party rights:</strong> Users are responsible for having rights to the inputs they provide and must not submit content that infringes others’ rights. Outputs may be similar to those received by others.</li>
              <li><strong>Competitive restrictions:</strong> Text/data mining, scraping, bulk export, or other harvesting of content/outputs for training, benchmarking, or competitive analysis is prohibited.</li>
            </ul>
          </Section>

          <Section title="Privacy and data">
            <ul className="list-disc list-inside space-y-3">
              <li><strong>Privacy Policy:</strong> The Privacy Policy is incorporated by reference and describes data practices, including categories of data collected, purposes, and user rights.</li>
              <li><strong>Training and improvement:</strong> Prompts and outputs are excluded from model training for all users. Vircle may still use data in limited ways for safety, abuse detection, debugging, analytics, and to operate core features, subject to the Privacy Policy.</li>
              <li><strong>Retention:</strong> After 1 year of account inactivity, Vircle may retain only account identifiers and purchase records required for tax/compliance, subject to backup and legal‑hold exceptions. Otherwise, deletion will proceed consistent with the Privacy Policy and applicable law.</li>
              <li><strong>Security:</strong> Vircle uses reasonable technical and organizational measures appropriate to the risk, such as encryption in transit/at rest, access controls, and monitoring. No method is 100% secure.</li>
            </ul>
          </Section>

          <Section title="Third‑party services and providers">
            <ul className="list-disc list-inside space-y-3">
                <li><strong>Vendors and models:</strong> The Service may rely on third‑party cloud hosting, authentication, analytics, crash reporting, content moderation services, and model providers. Use of certain features may be subject to additional acceptable‑use terms from such providers, which are flowed down to users where applicable.</li>
                <li><strong>Third‑party content:</strong> Vircle is not responsible for third‑party content, services, or links, and does not endorse them.</li>
            </ul>
          </Section>

          <Section title="Plans, pricing, and billing">
            <ul className="list-disc list-inside space-y-3">
                <li><strong>Plans:</strong> Free, Regular Texter (monthly), Regular Texter (annual), Heavy Chatter (monthly), Heavy Chatter (annual). Features, limits, and availability may vary by region or promotional period; current details appear in the app store listing.</li>
                <li><strong>Subscriptions and payments:</strong> Purchases, billing, auto‑renewal, cancellations, and refunds are handled by Apple App Store or Google Play. Manage subscriptions via the applicable store settings.</li>
                <li><strong>Promotions:</strong> Eligible new users receive a one‑time “free pack doubled for the first week.” Abuse or ineligibility may result in withdrawal of promotional benefits.</li>
                <li><strong>Taxes:</strong> Applicable taxes/VAT are handled by the app stores.</li>
            </ul>
          </Section>

          <Section title="Service changes, maintenance, and availability">
            <ul className="list-disc list-inside space-y-3">
              <li><strong>Changes:</strong> Vircle may modify or discontinue features at any time. Beta or experimental features are provided “as is,” may be rate‑limited, and may be removed without notice.</li>
              <li><strong>Maintenance and outages:</strong> Scheduled maintenance and third‑party outages may affect availability. Vircle may communicate incidents via in‑app notices when feasible. No service credits are offered for consumer plans.</li>
            </ul>
          </Section>

          <Section title="Intellectual property">
            <ul className="list-disc list-inside space-y-3">
              <li><strong>Vircle IP:</strong> The Service, including software, models, systems, code, features, trademarks, logos, and other proprietary content, is owned by Vircle and its licensors and is protected by law. No rights are granted except as expressly stated.</li>
              <li><strong>Trademarks:</strong> Users may not use Vircle’s name, logos, or marks without prior written permission, except for lawful nominative fair use.</li>
            </ul>
          </Section>

          <Section title="App store terms">
            <ul className="list-disc list-inside space-y-3">
              <li><strong>Store rules:</strong> App store rules govern in‑app purchases, subscription management, refunds, and certain content standards.</li>
              <li><strong>Third‑party beneficiaries:</strong> Apple Inc. and Google LLC (and their subsidiaries) are intended third‑party beneficiaries of applicable sections of these Terms and may enforce them.</li>
              <li><strong>Device/OS:</strong> Minimum supported OS versions may change; installing updates may be required.</li>
            </ul>
          </Section>

          <Section title="Export and sanctions">
            <p>
              Users represent they are not on any restricted lists and are not located in, under the control of, or a national or resident of any embargoed or sanctioned jurisdiction. Users agree to comply with applicable export, re‑export, and sanctions laws.
            </p>
          </Section>

          <Section title="Takedowns, IP complaints, and repeat infringers">
            <ul className="list-disc list-inside space-y-3">
              <li><strong>IP complaints:</strong> Send notices to <a href="mailto:info@vircle.ai" className="text-blue-400 hover:underline">info@vircle.ai</a> with sufficient detail to identify the work claimed infringed, the material at issue, contact details, and a statement of good‑faith belief and accuracy. Vircle may remove or disable access to alleged infringing material and notify the affected user.</li>
              <li><strong>Counter‑notice:</strong> Users may submit a counter‑notice with sufficient details and statements as required by law. Vircle may restore the material in accordance with applicable law and process.</li>
              <li><strong>Repeat infringers:</strong> Vircle may terminate accounts of repeat infringers in appropriate circumstances.</li>
            </ul>
          </Section>

          <Section title="Disclaimers">
            <p>
              The Service and all content, including AI outputs, are provided “as is” and “as available.” To the fullest extent permitted by law, Vircle disclaims all warranties, express or implied, including warranties of accuracy, non‑infringement, merchantability, fitness for a particular purpose, and quiet enjoyment. Vircle does not warrant uninterrupted, error‑free, or secure operation.
            </p>
          </Section>

          <Section title="Limitation of liability">
            <p>To the maximum extent permitted by law:</p>
            <ul className="list-disc list-inside space-y-3 pl-4">
              <li><strong>Indirect damages:</strong> Vircle will not be liable for any indirect, incidental, special, consequential, exemplary, or punitive damages, including lost profits, revenues, goodwill, data, or business interruption.</li>
              <li><strong>Paid users:</strong> Vircle’s aggregate liability arising out of or related to the Service will not exceed the amounts paid by the user to Vircle for the Service in the 12 months preceding the claim.</li>
              <li><strong>Free users:</strong> For users who have not paid fees, Vircle’s liability is limited to the maximum extent permitted by law.</li>
              <li><strong>Carve‑outs:</strong> The foregoing limitations do not apply to liability that cannot be limited under applicable law (e.g., fraud, willful misconduct). Additional compulsory protections may apply to consumers under local law.</li>
            </ul>
          </Section>

          <Section title="Indemnification">
            <ul className="list-disc list-inside space-y-3">
              <li><strong>User indemnity:</strong> Users will defend, indemnify, and hold harmless Vircle and its affiliates, officers, directors, employees, and agents from claims, damages, liabilities, costs, and expenses (including reasonable legal fees) arising from or related to: (a) user UGC or outputs used by the user; (b) violation of these Terms; (c) misuse of the Service; or (d) infringement or violation of rights of any person.</li>
              <li><strong>Vircle indemnity (IP):</strong> Vircle will defend users against third‑party claims alleging that the Service, as provided by Vircle and used per these Terms (excluding user inputs/UGC), directly infringes such third party’s intellectual property rights, and will pay final damages and reasonable legal fees awarded, provided the user promptly notifies Vircle, cooperates, and allows Vircle control of the defense. Vircle may procure rights, modify the Service, or terminate affected features with a refund of prepaid fees for the unused period as the sole remedy. This obligation does not apply to claims resulting from user content, combinations not provided by Vircle, or use contrary to documentation.</li>
            </ul>
          </Section>

          <Section title="Termination and suspension">
            <ul className="list-disc list-inside space-y-3">
              <li><strong>By user:</strong> The user may terminate at any time by deleting the account in‑app and canceling subscriptions via the app store.</li>
              <li><strong>By Vircle:</strong> Vircle may suspend or terminate access immediately for violations, safety, security, fraud, legal compliance, or to protect users or the Service. Vircle may also terminate for convenience with reasonable notice.</li>
              <li><strong>Effect:</strong> Upon termination, licenses granted to the user terminate, except as to rights that by nature survive. Vircle may allow a limited window for chat export upon request. Some content may persist in backups and logs for limited periods or where required by law.</li>
            </ul>
          </Section>

          <Section title="Changes to these Terms">
            <p>
              Vircle may modify these Terms. For material changes, Vircle will provide at least 15 days’ notice via in‑app notice and/or website posting (and email where available). Continued use after the effective date constitutes acceptance. Users who do not agree must stop using the Service before the changes take effect.
            </p>
          </Section>
          
          <Section title="Consumer rights and accessibility">
            <ul className="list-disc list-inside space-y-3">
              <li><strong>Consumer notices:</strong> Users may have mandatory consumer rights under local law (including EEA/UK/Türkiye digital content rules). Nothing in these Terms limits non‑waivable statutory rights.</li>
              <li><strong>Withdrawal:</strong> For digital services supplied immediately on request, statutory withdrawal rights may not apply or may be limited under applicable consumer law.</li>
              <li><strong>Accessibility:</strong> Vircle aims for best‑efforts accessibility and welcomes accessibility feedback at <a href="mailto:info@vircle.ai" className="text-blue-400 hover:underline">info@vircle.ai</a>.</li>
              <li><strong>Minors:</strong> The Service is not directed to children below app store minimum age thresholds. Where permitted, minors must use the Service under appropriate supervision and applicable consent requirements.</li>
            </ul>
          </Section>
          
          <Section title="Ownership of feedback">
            <p>
              Users grant Vircle a worldwide, perpetual, irrevocable, royalty‑free license to use and incorporate feedback, suggestions, or ideas without obligation or compensation.
            </p>
          </Section>

          <Section title="Assignment">
            <p>
              Users may not assign or transfer these Terms without Vircle’s prior written consent. Vircle may assign these Terms in connection with a merger, acquisition, corporate reorganization, or sale of assets.
            </p>
          </Section>

          <Section title="Force majeure">
            <p>
              Vircle will not be liable for delay or failure to perform due to events beyond its reasonable control, including acts of God, natural disasters, war, terrorism, riots, labor disputes, utility or network failures, third‑party service outages, or governmental actions.
            </p>
          </Section>

          <Section title="Severability; waiver; entire agreement; interpretation">
            <p>
              If any provision is held unenforceable, it will be modified to the minimum extent necessary or severed, and the remainder will remain in effect. Failure to enforce is not a waiver. These Terms, together with the Privacy Policy and any applicable in‑app policies, are the entire agreement and supersede prior agreements regarding the Service. Headings are for convenience only.
            </p>
          </Section>

          <Section title="Governing law and venue">
            <p>
              These Terms are governed by the laws of the Republic of Türkiye, without regard to conflict‑of‑laws principles. Exclusive venue and jurisdiction lie with the courts and enforcement offices of Istanbul, Türkiye. Users consent to personal jurisdiction in those courts.
            </p>
          </Section>

          <Section title="Notices and contact">
            <ul className="list-disc list-inside space-y-3">
              <li><strong>Legal and IP notices:</strong> <a href="mailto:info@vircle.ai" className="text-blue-400 hover:underline">info@vircle.ai</a></li>
              <li><strong>Registered address:</strong> [Insert full registered address line, district, and postal code, Istanbul, Türkiye]</li>
              <li><strong>Service and support inquiries:</strong> Via in‑app contact/reporting.</li>
            </ul>
          </Section>

          <Section title="Language">
            <p>
              If these Terms are provided in multiple languages, a designated language version will prevail in the event of conflict. Unless otherwise indicated, the governing language is English.
            </p>
          </Section>

          <Section title="App store terms supplement">
            <ul className="list-disc list-inside space-y-3">
              <li><strong>Apple App Store:</strong> Subscriptions, billing, and refunds are managed by Apple. Users must manage or cancel subscriptions in Apple ID settings. Apple is a third‑party beneficiary of these terms as to app distribution, in‑app purchases, and usage rules.</li>
              <li><strong>Google Play:</strong> Subscriptions, billing, and refunds are managed by Google. Users must manage or cancel subscriptions in Google Play settings. Google is a third‑party beneficiary as to app distribution, in‑app purchases, and usage rules.</li>
            </ul>
          </Section>

          <Section title="AI safety supplement">
            <ul className="list-disc list-inside space-y-3">
              <li><strong>Sensitive domains:</strong> Vircle may refuse, restrict, or apply safeguards to prompts/agents involving health, legal, finance, elections, minors, or other sensitive domains.</li>
              <li><strong>Emergency use:</strong> The Service is not intended for emergency or crisis use. For emergencies, contact local emergency services immediately.</li>
            </ul>
          </Section>

          <Section title="Brand and trademark rules">
            <p>
              “Vircle,” associated logos, and brand assets may not be used without written permission, except for nominative fair use, and must not be used in a way that implies endorsement, partnership, or sponsorship.
            </p>
          </Section>
          
          <Section title="Impersonation and synthetic media rules">
            <p>
              Impersonation requires clear, conspicuous disclosure and must not risk confusion or harm. Synthetic media that could mislead is restricted and may be removed. Vircle may require labels, adjust visibility, or disable features to mitigate risks.
            </p>
          </Section>

          <Section title="Data residency and cross‑border transfers">
            <p>
              Data may be processed in locations where Vircle and its service providers operate, subject to appropriate safeguards and compliance measures as described in the Privacy Policy.
            </p>
          </Section>

          <Section title="Public personas and content after termination">
            <p>
              If the Service enables public personas or shared content, Vircle may remove or anonymize public content after termination and retain minimal logs for fraud prevention, security, and legal compliance for limited periods.
            </p>
            <p className="italic mt-4">
              If any clause needs to be adjusted for regional disclosures or consumer‑specific language, say the word and an updated version will be provided promptly.
            </p>
          </Section>
        </div>

        <footer className="text-center text-gray-400 text-sm border-t border-gray-700 mt-12 pt-6">
          © {dateObj.getFullYear()} Itworked Systems. All rights reserved.
        </footer>
      </div>
    </div>
  );
};

export default TermsOfService;

